---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: testapp
  namespace: default
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/sanjeevrana-hp/argocd-app-config

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: testapp
  namespace: default
spec:
  interval: 30s
  path: ./dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: testapp

