---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: testapp
  namespace: default
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/sanjeevrana-hp/argocd-app-config

